"""empty message

Revision ID: 8516f67bde
Revises: None
Create Date: 2014-12-14 21:42:14.509195

"""

# revision identifiers, used by Alembic.
revision = '8516f67bde'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.String(length=1024), nullable=True))
    op.drop_column('files', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.VARCHAR(length=1024), nullable=True))
    op.drop_column('files', 'filename')
    ### end Alembic commands ###
